"""empty message

Revision ID: 528ddb279a88
Revises: 725216ecd92b
Create Date: 2024-06-12 16:37:21.465345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528ddb279a88'
down_revision = '725216ecd92b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
